version: '3.3'

services:
    mysql:
       image: mysql:8.0
       command: mysqld --default-authentication-plugin=mysql_native_password
       volumes:
         - database:/var/lib/mysql
       environment:
          MYSQL_ROOT_PASSWORD: pass
       ports:
         - "3306:3306"

    webserver:
      build:
        context: .
        dockerfile: webserver/Dockerfile
      volumes:
          - .:/var/www/html
          - ./webserver/symfonyHost.conf:/etc/apache2/sites-available/000-default.conf
      ports:
        - "8000:80"
      
volumes:
  database: